spring.application.name=backend
blockchain.difficulty=3
blockchain.mining-reward=10
blockchain.persistence.enabled=false
blockchain.persistence.type=file
blockchain.persistence.file=data/blockchain-chain.json
spring.datasource.url=jdbc:h2:file:./data/blockchain-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
